# Based on recipes from birdhouse and anaconda channel.

{% set name = "openjdk" %}
{% set version = "11.0.6" %}
{% set ver_parts = version.split('.') %}
{% set uversion = version.replace('.', '_') %}
{% set intellij_build = "765.1" %}
{% set build_number = 1 %}
{% set sha256_osx = "4f4005135ae5159d5a7e349c528e6038deba37a7099dd0d61c6025d6cc582186" %}
{% set sha256_jbrex_osx = "ce517092eb2cfd3aeed48144039e45cce0e7f4c26b7662bf73357669b818ef85" %}
{% set sha256_linux_64 = "91cd5109ad256bf2004da836314dfaf256fed100a5be681a74ea01bb8e9d154b" %}
{% set sha256_jbrex_linux_64 = "ac12430dcff3afa68830011aa2fde150d881ea2b56ba68c809d76a2d409c7708" %}
{% set sha256_linux_32 = "73e3428c54d2704c5518a5fafcd9d7758d41f6f38b4650836bc0a4a7a2aad4e1" %}
{% set sha256_jbrex_linux_32 = "d38e00dc9908f886d532ab243671a04bd993e58f5525c877697c632764dcf35f" %}
{% set sha256_dejagnu_fonts = "7576310b219e04159d35ff61dd4a4ec4cdba4f35c00e002a136f00e96a908b0a" %}
{% set sha256_win_64 = "f48da0f87f0ea34adebb93f4f1b31324a8d6186fea0815ac1b37237163482f8d" %}
{% set sha256_jbrex_win_64 = "6c2c097c6cb6c56ec906e030df0d652ad76f28769e05592f3a4d81463f384d3a" %}
{% set sha256_win_32 = "e8c1b9102440d9d11e707742884a947ea9390533611da6e4331a961476eca5fb" %}
{% set sha256_jbrex_win_32 = "95160b63d2640c7f5f583d574e44362414a033fd6c200e12b2eb9781147cbd26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://bintray.com/jetbrains/intellij-jbr/download_file?file_path=jbrsdk-{{ uversion }}-osx-x64-b{{ intellij_build }}.tar.gz      # [osx]
    fn: jbrsdk-{{ uversion }}-osx-x64-b{{ intellij_build }}.tar.gz                                                                          # [osx]
    sha256: {{ sha256_osx }}                                                                                                                                    # [osx]
  - url: https://bintray.com/jetbrains/intellij-jbr/download_file?file_path=jbr-{{ uversion }}-osx-x64-b{{ intellij_build }}.tar.gz      # [osx]
    fn: jbr-{{ uversion }}-osx-x64-b{{ intellij_build }}.tar.gz                                                                          # [osx]
    sha256: {{ sha256_jbrex_osx }}                                                                                                                              # [osx]
  - url: https://bintray.com/jetbrains/intellij-jbr/download_file?file_path=jbrsdk-{{ uversion }}-linux-x64-b{{ intellij_build }}.tar.gz    # [linux64]
    fn: jbrsdk-{{ uversion }}-linux-x64-b{{ intellij_build }}.tar.gz                                                                        # [linux64]
    sha256: {{ sha256_linux_64 }}                                                                                                                               # [linux64]
  - url: https://bintray.com/jetbrains/intellij-jbr/download_file?file_path=jbr-{{ uversion }}-linux-x64-b{{ intellij_build }}.tar.gz    # [linux64]
    fn: jbr-{{ uversion }}-linux-x64-b{{ intellij_build }}.tar.gz                                                                        # [linux64]
    sha256: {{ sha256_jbrex_linux_64 }}                                                                                                                         # [linux64]
  - url: https://bintray.com/jetbrains/intellij-jbr/download_file?file_path=jbrsdk-{{ uversion }}-linux-x86-b{{ intellij_build }}.tar.gz    # [linux32]
    fn: jbrsdk-{{ uversion }}-linux-x86-b{{ intellij_build }}.tar.gz                                                                        # [linux32]
    sha256: {{ sha256_linux_32 }}                                                                                                                               # [linux32]
  - url: https://bintray.com/jetbrains/intellij-jbr/download_file?file_path=jbr-{{ uversion }}-linux-x86-b{{ intellij_build }}.tar.gz    # [linux32]
    fn: jbr-{{ uversion }}-linux-x86-b{{ intellij_build }}.tar.gz                                                                        # [linux32]
    sha256: {{ sha256_jbrex_linux_32 }}                                                                                                                         # [linux32]
  - url: https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.zip                                                                 # [linux]
    sha256: {{ sha256_dejagnu_fonts }}                                                                                                                          # [linux]
    folder: fonts                                                                                                                                       # [linux]
  - url: https://bintray.com/jetbrains/intellij-jbr/download_file?file_path=jbrsdk-{{ uversion }}-windows-x64-b{{ intellij_build }}.tar.gz  # [win64]
    fn: jbrsdk-{{ uversion }}-windows-x64-b{{ intellij_build }}.tar.gz                                                                      # [win64]
    sha256: {{ sha256_win_64 }}                                                                                                                                 # [win64]
  - url: https://bintray.com/jetbrains/intellij-jbr/download_file?file_path=jbr-{{ uversion }}-windows-x64-b{{ intellij_build }}.tar.gz  # [win64]
    fn: jbr-{{ uversion }}-windows-x64-b{{ intellij_build }}.tar.gz                                                                      # [win64]
    sha256: {{ sha256_jbrex_win_64 }}                                                                                                                           # [win64]
  - url: https://bintray.com/jetbrains/intellij-jbr/download_file?file_path=jbrsdk-{{ uversion }}-windows-x86-b{{ intellij_build }}.tar.gz  # [win32]
    fn: jbrsdk-{{ uversion }}-windows-x86-b{{ intellij_build }}.tar.gz                                                                      # [win32]
    sha256: {{ sha256_win_32 }}                                                                                                                                 # [win32]
  - url: https://bintray.com/jetbrains/intellij-jbr/download_file?file_path=jbr-{{ uversion }}-windows-x86-b{{ intellij_build }}.tar.gz  # [win32]
    fn: jbr-{{ uversion }}-windows-x86-b{{ intellij_build }}.tar.gz                                                                      # [win32]
    sha256: {{ sha256_jbrex_win_32 }}                                                                                                                           # [win32]

build:
  number: {{ build_number }}
  # JDK 11 is not available for linux 32-bit, nor right now for windows 32-bit.
  skip: True  # [linux32 or win32]
  track_features:
    - openjdk
  rpath:
    - lib

requirements:
  build:
    - unzip  # [linux]
    - zip    # [linux]
  host:
    - zlib   # [unix]
 
test:
  requires:
    - {{ compiler('c') }}
  files:
    - test-jni     # [not win]
    - test-jni.sh  # [not win]
    - test-nio
  commands:
    - java -version
    - ./test-jni.sh                                # [not win]
    - conda inspect linkages -p ${PREFIX} openjdk  # [linux]
    - conda inspect objects -p ${PREFIX} openjdk   # [osx]

about:
  home: https://bintray.com/jetbrains/intellij-jbr
  license: GPLv2
  license_family: GPL
  summary: The JetBrains Runtime OpenJDK build.
  description: |
    JetBrains Runtime is a runtime environment for running
    IntelliJ Platform based products on Windows, Mac OS X, and Linux
  dev_url: https://github.com/JetBrains/jdk8u

extra:
  recipe-maintainers:
    - johanneskoester
    - mingwandroid
    - sodre
